public enum ActionResult {
	OK,
	
	BANK_EMPTY,
	
	COLONIST_RESERVE_EMPTY,
	PV_RESERVE_EMPTY,
	BUILDING_SLOTS_FULL,

	TRADER_FULL,
	TRADER_PLAYER_WITHOUT_GOODS,
	TRADER_DUPLICATE_GOODS,
	TRADER_PLAYER_REFUSE,

	BUILDER_PLAYER_WITHOUT_MONEY,
}
